### ISSUE TITLE
EtherCIS Dashboard "cache" ,ie DateTimeStamps etc 

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/Ripple-openEHR#3] opened 2017-06-15 17:07 UTC
Ian to update Rob - to tweak composition version.

**Comment by PhilBarrett** [comment] 2017-06-15 17:11
@robtweed 
This query appears to work on EtherCis
select e/ehr_id/value as ehrId, a/uid/value, a/context/other_context[at0001]/items[at0005]/value/magnitude as diagnosesCount, a/context/other_context[at0001]/items[at0008]/value/value as diagnosesDate, a/context/other_context[at0001]/items[at0002]/value/magnitude as ordersCount, a/context/other_context[at0001]/items[at0006]/value/value as ordersDate,
a/context/other_context[at0001]/items[at0004]/value/magnitude as resultsCount,
a/context/other_context[at0001]/items[at0009]/value/value as resultsDate,
a/context/other_context[at0001]/items[at0003]/value/magnitude as vitalsCount,
a/context/other_context[at0001]/items[at0007]/value/value as vitalsDate
from EHR e
contains COMPOSITION a[openEHR-EHR-COMPOSITION.ripple_cache.v1]
where e/ehr_id/value = 'ehrId'

**Comment by robtweed** [comment] 2017-06-16 10:04
This has been implemented on both the dev and demo machines, and Github & NPM have been updated

**Comment by PhilBarrett** [comment] 2017-06-19 08:53
@freshehr are you happy for this to be closed off now Ian?

**Comment by freshehr** [comment] 2017-06-19 10:57
Yes. All good AFAIK.

Ian

Dr Ian McNicoll
mobile +44 (0)775 209 7859
office +44 (0)1536 414994
skype: ianmcnicoll
email: ian@freshehr.com
twitter: @ianmcnicoll


Co-Chair, openEHR Foundation ian.mcnicoll@openehr.org
Director, freshEHR Clinical Informatics Ltd.
Director, HANDIHealth CIC
Hon. Senior Research Associate, CHIME, UCL

**Comment by tony-shannon** [comment] 2017-06-19 19:38
@PhilBarrett 
Can you help me recheck this please
I thought I noted empty columns when testing recently
thanks
T

**Comment by PhilBarrett** [comment] 2017-06-20 10:24
Checked on development environment and showcase environment and working fine

*Phil Barrett*
Director & Programme Manager
Ripple Foundation C.I.C <http://ripple.foundation>
+44 7941 529845
[image: Twitter]  <https://twitter.com/rippleosi> [image: LinkedIn]
<https://www.linkedin.com/company/ripple-foundation-c.i.c> [image: Github]
<https://github.com/RippleOSI>

**Comment by tony-shannon** [comment] 2017-06-20 15:12
Still not working properly from what I can see
See gaps here
![image](https://user-images.githubusercontent.com/939996/27340751-33fa4d9a-55d3-11e7-8703-4c7b70ee46a7.png)

**Comment by robtweed** [comment] 2017-06-20 15:20
To my knowledge the AQL run by the middle tier is correct.  I assume the issue is historical data Ian?

**Comment by freshehr** [comment] 2017-06-20 21:33
This is almost certainly due to the cache not being synced with older data. It should work properly once we start with a clean set of data.

**Comment by tony-shannon** [comment] 2017-06-21 11:32
this may be resolved by fixing test data issue
https://github.com/RippleOSI/Ripple-openEHR/issues/6

**Comment by tony-shannon** [comment] 2017-06-27 09:36
re Integer/Real Values , @ethercis please update this issue with Assembla #46 that would be great.

**Comment by tony-shannon** [comment] 2017-06-30 17:40
Rob has fixed the integer/real numbers issue in middleware for now.
Will close for now

**Closed as completed by tony-shannon** 2017-06-30 17:40 UTC
